In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

Creating Arrays
----------

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

Use of arange() function which start from 0 index
-

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(3.0)# this will print array in float value 

array([0., 1., 2.])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(20,10)

array([], dtype=int32)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [19]:
np.arange(30,20)

array([], dtype=int32)

In [21]:
b=np.arange(-30,20)
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [22]:
np.arange(10,10)

array([], dtype=int32)

In [23]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [24]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [25]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [26]:
nnp.arange(10,30,5,1)

NameError: name 'nnp' is not defined

use of zeros() function in numpy
-

In [27]:
np.zeros(2) # by sefault it will take float value 

array([0., 0.])

In [32]:
np.zeros_like(2)

array(0)

In [33]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [34]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [35]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [36]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [42]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n)) # parameter tunning

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [44]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [46]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


use of ones() Function
-

In [47]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [49]:
n

(5, 7)

In [50]:
np.ones(n1)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [53]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [55]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

Please Add new notbook & compare with np & *
-

In [57]:
#in simple 
from numpy import * # this means this call internally allthe 217 functionalities 


In [60]:
a=arange(3)
a


array([0, 1, 2])

In [61]:
type(a)

numpy.ndarray

In [62]:
range(12)

range(0, 12)

In [64]:
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [65]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [66]:
from numpy import*

In [67]:
zeros(5)

array([0., 0., 0., 0., 0.])

In [68]:
np.threes((3,2)) 

AttributeError: module 'numpy' has no attribute 'threes'

In [69]:
rand(3,2)

NameError: name 'rand' is not defined

In [71]:
np.random(3,2)

TypeError: 'module' object is not callable

In [72]:
np.random.rand(4)

array([0.18913248, 0.22132463, 0.27084269, 0.85289291])

In [73]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [74]:
np.random.rand(2,4)

array([[0.95799391, 0.70425374, 0.30524208, 0.05784989],
       [0.30356682, 0.92243575, 0.30797243, 0.90069577]])

In [82]:
np.random.randint(2,20)

15

In [84]:
np.random.randint(2,20)

4

In [86]:
np.random.randint(1,10,4)# this 4 vaule will print randomly between 1 to 9

array([4, 8, 9, 6])

In [93]:
np.random.randint(1,3,5)

array([1, 1, 2, 1, 1])

In [94]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [95]:
np.random.randint(1) 

0

In [96]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

6

In [98]:
np.random.randint(10,21,3)

array([19, 16, 19])

In [101]:
np.random.randint(1,12,10)

array([ 6,  5, 11,  7,  4, 10,  9,  9,  5,  7])

In [102]:
np.random.randint(1,12,(10,10))

array([[ 2, 10,  4, 11,  9,  6,  1,  9,  4,  5],
       [ 3,  8,  3,  8,  8,  6,  9,  4,  1,  3],
       [ 7,  3, 11,  4,  7,  6,  2,  7, 10,  8],
       [ 6,  3,  9,  2,  9,  2, 11,  2,  7, 10],
       [ 3,  9,  4,  4,  7,  9,  4,  5,  3,  1],
       [ 2,  4,  7, 11,  3, 10,  1,  9,  2,  7],
       [ 7,  2,  7,  4,  5, 10,  8,  9, 10,  5],
       [10,  7,  3, 11,  5,  5,  3,  8,  6,  2],
       [10,  7,  9, 10, 11,  2,  5,  9,  7, 10],
       [ 8, 10,  3,  4, 11,  7,  3,  9,  9,  6]])

In [103]:
np.random.randint(10,40,(10,10))

array([[23, 26, 22, 10, 33, 24, 38, 34, 21, 39],
       [33, 11, 13, 17, 36, 27, 31, 36, 12, 23],
       [16, 19, 28, 21, 16, 13, 14, 35, 12, 29],
       [11, 17, 14, 20, 14, 32, 35, 38, 19, 31],
       [31, 24, 10, 39, 15, 10, 32, 15, 25, 10],
       [20, 24, 27, 27, 17, 15, 11, 10, 31, 20],
       [13, 35, 26, 21, 33, 16, 17, 28, 19, 35],
       [36, 25, 13, 26, 14, 17, 12, 10, 38, 17],
       [35, 26, 37, 13, 34, 14, 15, 20, 23, 12],
       [14, 14, 22, 39, 10, 32, 25, 12, 17, 13]])

In [109]:
b=np.random.randint(10,20,(5,4))
b

array([[13, 11, 12, 11],
       [10, 10, 14, 10],
       [13, 12, 15, 16],
       [12, 15, 14, 14],
       [10, 15, 16, 14]])

In [110]:
b[:]

array([[13, 11, 12, 11],
       [10, 10, 14, 10],
       [13, 12, 15, 16],
       [12, 15, 14, 14],
       [10, 15, 16, 14]])

In [111]:
b[0:2]

array([[13, 11, 12, 11],
       [10, 10, 14, 10]])

In [112]:
b

array([[13, 11, 12, 11],
       [10, 10, 14, 10],
       [13, 12, 15, 16],
       [12, 15, 14, 14],
       [10, 15, 16, 14]])

In [113]:
b[0:-1]

array([[13, 11, 12, 11],
       [10, 10, 14, 10],
       [13, 12, 15, 16],
       [12, 15, 14, 14]])

In [114]:
b

array([[13, 11, 12, 11],
       [10, 10, 14, 10],
       [13, 12, 15, 16],
       [12, 15, 14, 14],
       [10, 15, 16, 14]])

In [115]:
b[0,2]

12

In [116]:
np.random.randint(10,20,(4,4))

array([[14, 14, 17, 19],
       [12, 18, 16, 16],
       [15, 14, 11, 16],
       [10, 11, 11, 17]])

Operation
-

In [129]:
a = np.random.randint(10,20,5)
a

array([13, 10, 11, 15, 12])

In [130]:
arr

array([0, 1, 2, 3, 4, 5])

In [131]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[17,  2, 87, 11, 66, 67, 36, 22, 12,  3],
       [52, 12, 73, 90, 32, 82, 81, 92, 71, 68],
       [46, 70, 96, 25, 63, 83,  6, 42, 28, 27],
       [68, 20, 88, 73,  4,  9, 59, 84, 20, 91],
       [63, 36, 95, 53, 58, 12, 57, 65, 72, 72],
       [15, 58, 17, 83, 71, 79, 75, 41, 14,  6],
       [69, 59, 31, 89,  7, 93, 10, 82,  4, 78],
       [43, 92, 37, 10, 78, 50, 41, 27, 37, 92],
       [65, 55, 11, 45, 27, 72, 48, 61, 42, 79],
       [50, 75, 64, 78, 50, 56, 53, 21, 63, 67]])

In [132]:
arr


array([0, 1, 2, 3, 4, 5])

In [133]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [134]:
arr[:4]

array([0, 1, 2, 3])

In [135]:
arr2[:]

array([[17,  2, 87, 11, 66, 67, 36, 22, 12,  3],
       [52, 12, 73, 90, 32, 82, 81, 92, 71, 68],
       [46, 70, 96, 25, 63, 83,  6, 42, 28, 27],
       [68, 20, 88, 73,  4,  9, 59, 84, 20, 91],
       [63, 36, 95, 53, 58, 12, 57, 65, 72, 72],
       [15, 58, 17, 83, 71, 79, 75, 41, 14,  6],
       [69, 59, 31, 89,  7, 93, 10, 82,  4, 78],
       [43, 92, 37, 10, 78, 50, 41, 27, 37, 92],
       [65, 55, 11, 45, 27, 72, 48, 61, 42, 79],
       [50, 75, 64, 78, 50, 56, 53, 21, 63, 67]])

In [136]:
arr2[0:5]

array([[17,  2, 87, 11, 66, 67, 36, 22, 12,  3],
       [52, 12, 73, 90, 32, 82, 81, 92, 71, 68],
       [46, 70, 96, 25, 63, 83,  6, 42, 28, 27],
       [68, 20, 88, 73,  4,  9, 59, 84, 20, 91],
       [63, 36, 95, 53, 58, 12, 57, 65, 72, 72]])

In [137]:
arr

array([0, 1, 2, 3, 4, 5])

In [139]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[75, 61, 91, 33, 60, 96, 47, 50, 44, 90],
       [28, 35, 53, 23, 26, 63, 95, 75, 93, 75],
       [88, 20,  4, 74, 61, 47, 38, 39, 46,  7],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [16, 24, 41, 54, 70, 70, 62, 25, 86, 85],
       [26, 96, 94, 26, 59, 43, 88, 29, 89, 81],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [96, 70, 98, 13, 99, 49, 51, 47, 44, 46],
       [16, 64, 53, 80, 54, 64, 54, 58,  9, 58],
       [ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19]])

In [140]:
arr2


array([[75, 61, 91, 33, 60, 96, 47, 50, 44, 90],
       [28, 35, 53, 23, 26, 63, 95, 75, 93, 75],
       [88, 20,  4, 74, 61, 47, 38, 39, 46,  7],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [16, 24, 41, 54, 70, 70, 62, 25, 86, 85],
       [26, 96, 94, 26, 59, 43, 88, 29, 89, 81],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [96, 70, 98, 13, 99, 49, 51, 47, 44, 46],
       [16, 64, 53, 80, 54, 64, 54, 58,  9, 58],
       [ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19]])

In [141]:
arr2[1,5]

63

In [142]:
arr2

array([[75, 61, 91, 33, 60, 96, 47, 50, 44, 90],
       [28, 35, 53, 23, 26, 63, 95, 75, 93, 75],
       [88, 20,  4, 74, 61, 47, 38, 39, 46,  7],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [16, 24, 41, 54, 70, 70, 62, 25, 86, 85],
       [26, 96, 94, 26, 59, 43, 88, 29, 89, 81],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [96, 70, 98, 13, 99, 49, 51, 47, 44, 46],
       [16, 64, 53, 80, 54, 64, 54, 58,  9, 58],
       [ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19]])

In [143]:
arr2[-5,-5]

43

In [145]:
arr2[-1,-2]

54

In [146]:
arr2

array([[75, 61, 91, 33, 60, 96, 47, 50, 44, 90],
       [28, 35, 53, 23, 26, 63, 95, 75, 93, 75],
       [88, 20,  4, 74, 61, 47, 38, 39, 46,  7],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [16, 24, 41, 54, 70, 70, 62, 25, 86, 85],
       [26, 96, 94, 26, 59, 43, 88, 29, 89, 81],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [96, 70, 98, 13, 99, 49, 51, 47, 44, 46],
       [16, 64, 53, 80, 54, 64, 54, 58,  9, 58],
       [ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19]])

In [148]:
arr2[::-1]

array([[ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19],
       [16, 64, 53, 80, 54, 64, 54, 58,  9, 58],
       [96, 70, 98, 13, 99, 49, 51, 47, 44, 46],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [26, 96, 94, 26, 59, 43, 88, 29, 89, 81],
       [16, 24, 41, 54, 70, 70, 62, 25, 86, 85],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [88, 20,  4, 74, 61, 47, 38, 39, 46,  7],
       [28, 35, 53, 23, 26, 63, 95, 75, 93, 75],
       [75, 61, 91, 33, 60, 96, 47, 50, 44, 90]])

In [150]:
arr2

array([[75, 61, 91, 33, 60, 96, 47, 50, 44, 90],
       [28, 35, 53, 23, 26, 63, 95, 75, 93, 75],
       [88, 20,  4, 74, 61, 47, 38, 39, 46,  7],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [16, 24, 41, 54, 70, 70, 62, 25, 86, 85],
       [26, 96, 94, 26, 59, 43, 88, 29, 89, 81],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [96, 70, 98, 13, 99, 49, 51, 47, 44, 46],
       [16, 64, 53, 80, 54, 64, 54, 58,  9, 58],
       [ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19]])

In [152]:
arr2[::-2]

array([[ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19],
       [96, 70, 98, 13, 99, 49, 51, 47, 44, 46],
       [26, 96, 94, 26, 59, 43, 88, 29, 89, 81],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [28, 35, 53, 23, 26, 63, 95, 75, 93, 75]])

In [153]:
arr2[::-3]

array([[ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [75, 61, 91, 33, 60, 96, 47, 50, 44, 90]])

In [154]:
arr2

array([[75, 61, 91, 33, 60, 96, 47, 50, 44, 90],
       [28, 35, 53, 23, 26, 63, 95, 75, 93, 75],
       [88, 20,  4, 74, 61, 47, 38, 39, 46,  7],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [16, 24, 41, 54, 70, 70, 62, 25, 86, 85],
       [26, 96, 94, 26, 59, 43, 88, 29, 89, 81],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [96, 70, 98, 13, 99, 49, 51, 47, 44, 46],
       [16, 64, 53, 80, 54, 64, 54, 58,  9, 58],
       [ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19]])

In [155]:
arr2[::-3]

array([[ 6, 74, 27, 69, 38, 65,  5, 81, 54, 19],
       [19, 77,  4, 54, 48, 90, 86, 60, 97, 26],
       [41, 73,  1, 85, 85, 68, 96, 77, 31, 48],
       [75, 61, 91, 33, 60, 96, 47, 50, 44, 90]])

In [156]:
arr

array([0, 1, 2, 3, 4, 5])

In [158]:
arr.max()

5

In [159]:
arr.min()

0

In [164]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [165]:
from numpy import *

In [166]:
a=array([1,2,3,4,9])

In [167]:
median(a)

3.0

In [168]:
median(arr)

2.5

In [169]:
arr

array([0, 1, 2, 3, 4, 5])

In [170]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [171]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [172]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [173]:
arr.reshape(1,5) # this will not becuase array size is 6 this cannot be reshape in (1,5)

ValueError: cannot reshape array of size 6 into shape (1,5)

In [174]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [175]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [176]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

INDEXING
-

In [177]:
mat=np.arange(0,100).reshape(10,10)

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
row=4
col=5

In [180]:
col

5

In [181]:
row

4

In [182]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
mat[row,col]

45

In [184]:
mat[4,5]

45

In [185]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [186]:
col=6

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [189]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [190]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [191]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [193]:
col

6

In [194]:
row

4

In [195]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [196]:
row

4

In [197]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [199]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [202]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [203]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [204]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [205]:
row

4

In [206]:
col

6

In [207]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [208]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat[1,4]

14

In [210]:
mat[3,5]

35

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[1,4]

14

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [216]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [218]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [219]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [220]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [222]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [228]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [229]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
mat[0,1]

1

In [231]:
mat[1,6]

16

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [234]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [235]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [237]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [238]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [239]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [240]:
mat[3,5]

35

In [241]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [242]:
mat[1:2,2:4]

array([[12, 13]])

In [243]:
mat[2:3,2:3]

array([[22]])

In [244]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [245]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [246]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [247]:
mat[2:3,4:5]

array([[24]])

mat # we also called as filter
-

In [248]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [249]:
id(mat)

2195273435440

In [250]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [251]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [252]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [253]:
mat[mat==50]

array([50])

In [254]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [255]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a2=mat[mat