Slicing in matrix
--------------------


In [1]:
import numpy as np


In [2]:
b=np.random.randint(10,20,(5,4))

In [3]:
b

array([[12, 10, 11, 12],
       [18, 16, 15, 14],
       [19, 16, 16, 13],
       [14, 16, 13, 15],
       [10, 19, 10, 14]])

In [4]:
type(b)

numpy.ndarray

In [5]:
b[:]

array([[12, 10, 11, 12],
       [18, 16, 15, 14],
       [19, 16, 16, 13],
       [14, 16, 13, 15],
       [10, 19, 10, 14]])

In [6]:
b[1:3]

array([[18, 16, 15, 14],
       [19, 16, 16, 13]])

In [7]:
b[1,2]

15

In [8]:
b

array([[12, 10, 11, 12],
       [18, 16, 15, 14],
       [19, 16, 16, 13],
       [14, 16, 13, 15],
       [10, 19, 10, 14]])

In [9]:
b[1,3]


14

In [10]:
b[1,-1]

14

In [11]:
b[2:3]

array([[19, 16, 16, 13]])

In [12]:
b

array([[12, 10, 11, 12],
       [18, 16, 15, 14],
       [19, 16, 16, 13],
       [14, 16, 13, 15],
       [10, 19, 10, 14]])

In [13]:
b[0,-2]


11

In [14]:
b[0:-2]

array([[12, 10, 11, 12],
       [18, 16, 15, 14],
       [19, 16, 16, 13]])

In [15]:
b

array([[12, 10, 11, 12],
       [18, 16, 15, 14],
       [19, 16, 16, 13],
       [14, 16, 13, 15],
       [10, 19, 10, 14]])

In [16]:
b[0,2]

11

In [17]:
b[-5,-3]


10

In [18]:
b

array([[12, 10, 11, 12],
       [18, 16, 15, 14],
       [19, 16, 16, 13],
       [14, 16, 13, 15],
       [10, 19, 10, 14]])

In [19]:
b[-4,2]

15

operation
-----

In [24]:
a=np.random.randint(10,20,20)
a

array([10, 18, 19, 13, 15, 12, 11, 10, 13, 14, 18, 12, 18, 17, 11, 17, 16,
       14, 15, 11])

In [22]:
__name__

'__main__'

In [29]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[48, 78,  5, 42, 69, 51, 41, 77, 55, 52],
       [ 6, 41, 56, 91, 12, 28, 40, 88,  5, 52],
       [24, 80, 54, 54, 88, 51, 14, 90, 44, 55],
       [66, 20, 32, 82, 73, 31, 84,  6, 60, 58],
       [90, 35, 59, 31, 53,  5, 54, 13, 13, 13],
       [33, 88, 38, 37, 33, 31, 85, 89, 94, 93],
       [ 8, 47,  6, 77, 96, 11, 28, 52, 28, 20],
       [30, 54, 12, 35, 40, 28, 99, 78, 97, 79],
       [95,  0, 63, 81, 80, 71, 46, 50, 95, 30],
       [80, 44, 73,  2, 10, 76, 17, 51, 68, 59]])

In [30]:
arr2[:,6]# print Coulum

array([41, 40, 14, 84, 54, 85, 28, 99, 46, 17])

In [31]:
arr2[6,:]

array([ 8, 47,  6, 77, 96, 11, 28, 52, 28, 20])

In [32]:
arr2[6]

array([ 8, 47,  6, 77, 96, 11, 28, 52, 28, 20])